import os

CABOT_FROM_EMAIL = os.environ.get('CABOT_FROM_EMAIL', 'from@example.com')
GRAPHITE_API = os.environ.get('GRAPHITE_API', 'http://graphite.example.com/')
GRAPHITE_USER = os.environ.get('GRAPHITE_USER', 'user')
GRAPHITE_PASS = os.environ.get('GRAPHITE_PASS', 'password')
JENKINS_API = os.environ.get('JENKINS_API', 'https://jenkins.example.com/')
JENKINS_USER = os.environ.get('JENKINS_USER', 'username')
JENKINS_PASS = os.environ.get('JENKINS_PASS', 'password')
HIPCHAT_ALERT_ROOM = os.environ.get('HIPCHAT_ALERT_ROOM', '48052')
HIPCHAT_API_KEY = os.environ.get('HIPCHAT_API_KEY', 'your_hipchat_api_key')
HIPCHAT_URL = os.environ.get('HIPCHAT_URL', 'https://api.hipchat.com/v1/rooms/message')
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', 'your_account_sid')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', 'your_auth_token')
TWILIO_OUTGOING_NUMBER = os.environ.get('TWILIO_OUTGOING_NUMBER', '+14155551234')
CALENDAR_ICAL_URL = os.environ.get('CALENDAR_ICAL_URL', 'http://www.google.com/calendar/ical/example.ics')
WWW_HTTP_HOST = os.environ.get('WWW_HTTP_HOST', 'cabot.example.com')
ALERT_INTERVAL = os.environ.get('ALERT_INTERVAL', 10)
NOTIFICATION_INTERVAL = os.environ.get('NOTIFICATION_INTERVAL', 120)
